version: "3.5"
services:
  elastics:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: es
    environment:
        cluster.name: development
        node.name: winner
        bootstrap.memory_lock: false
        network.host: 0.0.0.0
        discovery.zen.minimum_master_nodes: 1
        ES_JAVA_OPTS: -Xms1g -Xmx1g
        discovery.type: single-node
        xpack.security.enabled: false
    ports:
      - 9200:9200
    networks:
      - searcher_net
  
  app:
    build: .
    image: liroygenkins/test-task:v1
    container_name: app
    ports:
      - "8000:8000"
    restart: on-failure
    command: python3 main.py
    depends_on:
      - elastics
    ports:
      - 8000:8000
    networks:
        - searcher_net
      
networks:
    searcher_net:
        driver: bridge